baseURL: https://jalcocert.github.io/
languageCode: en-us
title: RPi
theme: cupper-hugo-theme

params:
  description: RPi A-Z Setup and Projects.
  homeMetaContent: RPi A-Z Setup and Projects.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Github](https://github.com/JAlcocerT/RPi).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: JAlcocerT
  katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: First Steps
      url: /post/
      weight: 2
    - name: Projects
      url: /projects/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4            
    - name: About
      url: /about/
      weight: 5          