mqtt:
  enabled: false

detectors:
  cpu1:
    type: cpu
    num_threads: 2

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

cameras:
  picam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://host.docker.internal:8654/picam
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    record:
      enabled: false
    snapshots:
      enabled: true
      retain:
        default: 2
    motion:
      threshold: 30

objects:
  track:
    - person
version: 0.17-0
