
version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1889:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - /home/Docker/thingsboard/data:/data
      - /home/Docker/thingsboard/var:/var/log/thingsboard
      
#https://thingsboard.io/docs/user-guide/install/docker/
#https://github.com/thingsboard/thingsboard