services:
  mediamtx:
    image: bluenviron/mediamtx:latest-rpi
    container_name: mediamtx
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - /run/udev:/run/udev:ro
      - /dev:/dev

  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    shm_size: "128mb"
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml
      - ./storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    depends_on:
      - mediamtx
