
version: '3'
services:
  dht_sensor_app:
    image: dht11_python_to_influxdb
    container_name: dht_sensor_app
    privileged: true
    depends_on:
      - influxdb
    command: ["python", "Python2InfluxDB.py"]
    #command: tail -f /dev/null #keep it running
    environment:
      - INFLUXDB_HOST=http://127.0.0.1
      - INFLUXDB_PORT=8086
      - INFLUXDB_DBNAME=sensor_data
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=mysecretpassword      

  influxdb:
    image: influxdb:1.8 #for arm32/64 #latest for ARM64
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sensor_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=mysecretpassword

  grafana:
    image: grafana/grafana:9.5.7 #was using this one instead of latest for stability
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana  # Add this line to specify the volume

volumes:
  influxdb_data:
  grafana_data:  # Define the volume for Grafana